/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package dialogModals;

import javax.swing.JOptionPane;
import controlador.ProveedorControlador;
import modelo.Proveedor;
import utils.Validator;
import vista.dashboard.ClientePage;
import vista.dashboard.ProveedorPage;

/**
 *
 * @author intel
 */
public class ManageProveedorModal extends javax.swing.JDialog {

    /**
     * Creates new form AddCategoriaModal
     */
    public ManageProveedorModal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    private String idProveedor;
    
    public ManageProveedorModal(java.awt.Frame parent, boolean modal, String id) {
        super(parent, modal);
        Proveedor proveedor = ProveedorControlador.obtenerProveedor(id);
        
        initComponents();
        
        jLabel1.setText("Editar Proveedor");
        nameInput.setValue(proveedor.getNombre());
        emailInput.setValue(proveedor.getEmail());
        telefonoInput.setValue(proveedor.getTelefono());
        direccionInput.setValue(proveedor.getDireccion());
        
        jButton1.setText("Guardar");
        
        this.idProveedor = id;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nameInput = new components.jInput("Ingrese el nombre");
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new components.jButton();
        emailInput = new components.jInput("Ingrese el email");
        jLabel5 = new javax.swing.JLabel();
        telefonoInput = new components.jInput("Ingrese el teléfono");
        jLabel7 = new javax.swing.JLabel();
        direccionInput = new components.jInput("Ingrese la dirección");
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Crear Proveedor");

        nameInput.setText("Ingrese el nombre");

        jLabel2.setText("Nombre");

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        emailInput.setText("Ingrese el email");

        jLabel5.setText("Email");

        telefonoInput.setText("Ingrese el teléfono");

        jLabel7.setText("Teléfono");

        direccionInput.setText("Ingrese la dirección");

        jLabel8.setText("Dirección");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(nameInput, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addComponent(emailInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7)
                            .addComponent(telefonoInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(direccionInput, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direccionInput, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailInput, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telefonoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (idProveedor != null)
            editarProveedor();
        else
            crearNuevoProveedor();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void crearNuevoProveedor() {
        try {
            Proveedor proveedor = new Proveedor();
            
            String nombre = nameInput.getValue();
            String email = emailInput.getValue();
            String telefono = telefonoInput.getValue();
            String direccion = direccionInput.getValue();
            
            if (nombre.isEmpty() || email.isEmpty() || telefono.isEmpty())
                throw new Exception("Complete todos los campos");
            
            Validator.EMAIL(email);
            Validator.TELEFONO(telefono);
            
            proveedor.setNombre(nombre);
            proveedor.setEmail(email);
            proveedor.setTelefono(telefono);
            proveedor.setDireccion(direccion);
            
            if (ProveedorControlador.crearProveedor(proveedor)) {
                // Si la categoría se crea con éxito, muestra un mensaje de éxito
                JOptionPane.showMessageDialog(null, "Registro guardado");
                ProveedorPage.recagarTabla();
                dispose();
            } else {
                // Si hay un error al crear la categoría, muestra un mensaje de error
                JOptionPane.showMessageDialog(null, "Error al guardar");
            }
        } catch (Exception error) {
            JOptionPane.showMessageDialog(null, error.getMessage());
        }
    }
    
    private void editarProveedor() {
        try {
        Proveedor proveedor = new Proveedor();
        
        String nombre = nameInput.getValue();
        String email = emailInput.getValue();
        String telefono = telefonoInput.getValue();
        String direccion = direccionInput.getValue();
        
        if (nombre.isEmpty() || email.isEmpty() || telefono.isEmpty())
            throw new Exception("Complete todos los campos");
        
        Validator.EMAIL(email);
        Validator.TELEFONO(telefono);
        
        proveedor.setId(Integer.parseInt(idProveedor));
        proveedor.setNombre(nombre);
        proveedor.setEmail(email);
        proveedor.setTelefono(telefono);
        proveedor.setDireccion(direccion);
        
        if (ProveedorControlador.actualizarProveedor(proveedor)) {
            // Si la categoría se crea con éxito, muestra un mensaje de éxito
            JOptionPane.showMessageDialog(null, "Registro guardado");
            ProveedorPage.recagarTabla();
            dispose();
        } else {
            // Si hay un error al crear la categoría, muestra un mensaje de error
            JOptionPane.showMessageDialog(null, "Error al guardar");
        }
        } catch (Exception error){
            JOptionPane.showMessageDialog(null, error.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ManageProveedorModal dialog = new ManageProveedorModal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private components.jInput direccionInput;
    private components.jInput emailInput;
    private components.jButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private components.jInput nameInput;
    private components.jInput telefonoInput;
    // End of variables declaration//GEN-END:variables
}
